export const lang = {
  English: [
    "What is your name?",
    "How are you!",
    "Afghanistan",
    "Apple!!!",
    "Dear sir/madam,",
    "Best Regard",
    "Germany",
    "187$53",
    "/>,@!fsadfd",
    "With the guide of a word bank",
    "USA",
    "Mojeeb Rahman",
    "Love you",
    "Gaming 007",
    "Sentences in these worksheets",
    "0987+3425",
    "Enter",
    "I am in University right now!",
    "google",
    "Complete the sentences ",
    "Summer Review Packets!",
    "You are signed out",
    "Sign in to get the best experience",
  ],
  Dari: [
    "نام شما چیست؟",
    "چطور هستین",
    "افغانستان",
    "سیب!!!",
    "آقا / خانم عزیز",
    "با احترام",
    "جرمنی",
    "من ترا دوست دارم",
    "من ترا ازبین خواهم بورد",
    "پسر خوب",
  ],
  Deutsche: [
    "Wie Heißen Sie?",
    "gibt mir fünf!!!!",
    "Deutschland",
    "Berliner",
    "Ich heiße Mojeeb",
    "Lachen ist night kosted, aber es ist viel wert",
    "kochen",
    "weinen",
    "Wie geths?",
    "Ich liebe dich!",
    "Ich liebe Afghanistan",
    "Es tut mir Leid",
    "Du bist sehr schön!",
    "Ich mag dich nicht.",
  ],
};
